C     *******************************************************************
C
C       SPGETSEQ - Enumerate sparse grid level index sequences.
C
C       License:
C            Sparse Grid Interpolation Toolbox
C            Copyright (c) 2006 W. Andreas Klimke, Universitaet Stuttgart
C            Copyright (c) 2007-2008 W. A. Klimke. All Rights Reserved.
C            Copyright (c) 2026 eggzec. All Rights Reserved.
C            See LICENSE for details.
C
C     *******************************************************************

      SUBROUTINE SPGETSEQ(N, D, NLEVELS, SEQ)
C     *******************************************************************
C
C       SPGETSEQ enumerates all multi-index tuples (l_1,...,l_D)
C       with l_1 + ... + l_D = N and l_i >= 0.
C
C       The first row always has l_1 = N, l_i = 0 for i > 1.
C       Subsequent rows are generated by the Klimke lexicographic
C       shift algorithm (Stuttgart convention).
C
C       Parameters:
C
C         Input,  INTEGER N              - level
C         Input,  INTEGER D              - dimension
C         Input,  INTEGER NLEVELS        - C(N+D-1,D-1), pre-computed
C         Output, INTEGER SEQ(NLEVELS,D) - multi-index array
C
C     *******************************************************************

      IMPLICIT NONE

      INTEGER N, D, NLEVELS
      INTEGER SEQ(NLEVELS, D)

      INTEGER K, L, M, IMAX, ISUM, ITEMP

      DO L = 1, D
            SEQ(1, L) = 0
      END DO
      SEQ(1, 1) = N
      IMAX = N

      DO 100 K = 2, NLEVELS

            DO L = 1, D
                  SEQ(K, L) = 0
            END DO

            IF (SEQ(K-1, 1) .GT. 0) THEN

C                 First entry positive: decrement it, bump next eligible dim.
                  SEQ(K, 1) = SEQ(K-1, 1) - 1
                  DO L = 2, D
                        IF (SEQ(K-1, L) .LT. IMAX) THEN
                              SEQ(K, L) = SEQ(K-1, L) + 1
                              DO M = L+1, D
                                    SEQ(K, M) = SEQ(K-1, M)
                              END DO
                              GOTO 100
                        END IF
                  END DO

            ELSE

C                 First entry is zero: roll over to next row group.
                  ISUM = 0
                  DO L = 2, D
                        IF (SEQ(K-1, L) .LT. IMAX) THEN
                              SEQ(K, L) = SEQ(K-1, L) + 1
                              ISUM = ISUM + SEQ(K, L)
                              DO M = L+1, D
                                    SEQ(K, M) = SEQ(K-1, M)
                                    ISUM = ISUM + SEQ(K, M)
                              END DO
                              GOTO 50
                        ELSE
                              ITEMP = 0
                              DO M = L+2, D
                                    ITEMP = ITEMP + SEQ(K-1, M)
                              END DO
                              IMAX = N - ITEMP
                              SEQ(K, L) = 0
                        END IF
                  END DO

 50               SEQ(K, 1) = N - ISUM
                  IMAX = N - ISUM

            END IF

 100  CONTINUE

      RETURN
      END
